### ISSUE TITLE
What is the every bands of the predictors.tif meaning?

### ISSUE THREAD

**Issue by hulaba** [pansism/downscale-satelliteLST#2]
Hello!Thanks for your nice work!
I have a question that what is the every bands of the predictors.tif meaning,I guess NDVI  and DEM data maybe in it, but I don't the others. Could you please give me an answer?Also, where can I find the class reference paper to read?
Best wishes to you!

**Comment by pansism** [comment]
The predictors in the example are the PCAs derived from DEM, NDVI, Albedo, the three Annual Cycle Parameters (ACPs) and an LST image. You can find brief description of this algorithm in the attached presentation.

[AGU_presentation_v3.pdf](https://github.com/pansism/downscale-satelliteLST/files/4475316/AGU_presentation_v3.pdf)

Kind regards,
Panagiotis
