### ISSUE TITLE
when i test use example tif, a warning appeared

### ISSUE THREAD

**Issue by douyoujun** [pansism/downscale-satelliteLST#3]
Warning 1: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.

i don't know what caused this warning, which will make an impact on the result?
![image](https://user-images.githubusercontent.com/37895452/82274970-33c60580-99b4-11ea-96e9-b301159760a2.png)

and you provided a predictor sample file "LST_predictors_100m.tif" as referrence downscaling background, if i want to downscale to another scales,i must provide the corresponding referrence files,which may be hard to provide sometimes.

**Comment by pansism** [comment]
Hi, It's a GDAL warning and it will not affect your results. To learn more about it, check this [post](https://gis.stackexchange.com/questions/350084/warning1-tiffreaddirectorysum-of-photometric-type-related-color-channels).

Regarding your second question, unfortunately, my code does not offer this functionality and the user has to prepare all the input data beforehand by himself/herself.
