### ISSUE TITLE
Example script throws error

### ISSUE THREAD

**Issue by pramitghosh** [pansism/downscale-satelliteLST#4]
Hi. First, thanks for writing this class. Unfortunately when I try to run the example script (example_using_SEVIRI_data.py),
```python
%Run example_using_SEVIRI_data.py
```
I encounter the following. I am using version 1.1.0 of your code with Python 3.9.5.
```
Warning 1: LSALST_20180819_Athens_15min.tif: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.
Warning 1: TIFFReadDirectory:Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples.

Downscaling started at:   21/01/2022, 12:56

SETTINGS
========
Residual Correction:           True
R2-threshold:                  0.5
Missing pxls threshold:        40.0%
Train/test size split:         0.7/0.3
Parallel jobs:                 1
Hyperarameter tuning trials:   60

Building the regression models.
  Processing band 0:
Traceback (most recent call last):
  File "/home/pramit/Downloads/downscale-satelliteLST-1.1.0/example/example_using_SEVIRI_data.py", line 45, in <module>
    main()
  File "/home/pramit/Downloads/downscale-satelliteLST-1.1.0/example/example_using_SEVIRI_data.py", line 32, in main
    data.ApplyDownscaling(residual_corr=True)
  File "/home/pramit/Downloads/downscale-satelliteLST-1.1.0/example/DownscaleSatelliteLST.py", line 246, in ApplyDownscaling
    normal_transformer = QuantileTransformer(len(y)//2, "normal", random_state=self.SEED).fit(X)
TypeError: __init__() takes 1 positional argument but 3 positional arguments (and 1 keyword-only argument) were given
```
Given that Python is not my go-to language, it would be of much help if you could please point out if I am doing something wrong. Thanks!

**Comment by pansism** [comment]
Hi! You are probably using the newest version of scikit (I guess v.1.0.x, correct?).

Haven't tested it, but updating line 246 to `normal_transformer = QuantileTransformer(n_quantiles=len(y)//2, output_distribution="normal", random_state=self.SEED).fit(X)`, should fix your problem.

What I recommend, however, is to make a new python environment with scikit 0.22 and use this. 

Please let me know if it works

**Comment by pramitghosh** [comment]
Hi. Thanks for your quick response. You were right that I was using scikit v1.0.2.

I haven't tried it with scikit v0.22 but changing Line 246 to your suggestion fixes the problem and makes the script work as desired with the new version of scikit.

Many thanks, once again! :-)
