### ISSUE TITLE
about data

### ISSUE THREAD

**Issue by zhinan1222** [pansism/downscale-satelliteLST#6]
Could you tell me how this predictor was made，please

**Comment by zhinan1222** [comment]
Do you have relevant literature for this code

**Comment by pansism** [comment]
Hi @zhinan1222,

I have presented this work n [AGU's 2019 Fall Meeting](https://ui.adsabs.harvard.edu/abs/2019AGUFMGC44C..02S/abstract).

You can find a brief description of the algorihtm and some information about the example in this [pdf](https://github.com/pansism/downscale-satelliteLST/files/8695826/AGU_presentation_v3.pdf).

If you use it, please cite:
1. Sismanidis, P., Keramitsoglou, I., Hulley, G. C., & Kiranoudis, C. T. (2019, December). Enhancing the spatial resolution of diurnal LST from geostationary satellites. In AGU Fall Meeting Abstracts (Vol. 2019, pp. GC44C-02).
2. Sismanidis, P. (2018). Applying computational methods for processing thermal satellite images of urban areas. Doctoral dissertation. National Technical University of Athens.

Kind regards,
Panagiotis
